### ISSUE TITLE
Staff API endpoints return 404

### ISSUE THREAD

**Issue by kimburgess** [place-labs/partner-environment#41]
Changes introduced in e2469d81027a7c7653430fd74cab36a2c2feb46e added mapping to a local nginx config. This is not compatible with the rest of the environment.

Until this time the following config was in use: https://github.com/PlaceOS/nginx/blob/staff-api/config/nginx.conf.

Configuration changes introduced for logspout, metricbeat should be migrated into the nginx repo, or alternatively local config here reworks to include both of these requirement.

**Comment by w-le** [comment]
yeah so it's due to this
https://github.com/place-labs/partner-environment/blob/master/docker-compose.yml#L405

we should just get rid placeos/nginx staff-api branch (i created it as a temporary workaround to placeos/nginx's nginx.conf not having upstream `staff`) and just have placeos/nginx master branch have upstream nginx but in a way that doesn't fail is staff container is not present.

**Comment by kimburgess** [comment]
Resolved via https://github.com/place-labs/partner-environment/commit/d524a4d7ba67672a95f7b015698ff8fea8bdcadf.
