### ISSUE TITLE
Autogen development secrets

### ISSUE THREAD

**Issue by kimburgess** [place-labs/partner-environment#8]
The current setup ships with a:
1. [default user/pass](https://github.com/place-labs/partner-environment/blob/b6d9f0b55730147ca5476f1f38701346a9f561c6/docker-compose.yml#L163-L164)
2. [default PSK for the dispatch service](https://github.com/place-labs/partner-environment/blob/b6d9f0b55730147ca5476f1f38701346a9f561c6/docker-compose.yml#L200)
3. and [references for other default secrets](https://github.com/place-labs/partner-environment/blob/b6d9f0b55730147ca5476f1f38701346a9f561c6/docker-compose.yml#L61-L62)

These should all be securely auto-generated for each environment and _never_ fall back to a common default. If they are not available (have not been defined, are blank etc), the environment should fail to boot.

**Comment by caspiano** [comment]
Any suggestions for a neat solution?

**Comment by KimBurgess** [comment]
I've been playing around with a few approaches. What looks to be the simplest (without introducing additional tooling such as [Vault](https://www.vaultproject.io/)) is to switch these across to [docker secrets](https://docs.docker.com/compose/compose-file/#secrets). These are now supported as part of standalone docker-compose without needing swarm. This would require a change to the various services reading these to look at `/run/secrets/<name>` instead of the env var (or modify the container to export from the secrets file to env), but this setup maps across neatly to volume based secret mounts in Kubernetes so may be a nice change regardless.

If they are set as file based secrets, docker-compose will fail to bring up the project if the mapped file does not exist. It gives a pretty readable error for this too.

The `./install` script would then need to be expanded to create the associated secrets (using `/dev/urandom` / openssl / combinations from a wordlist / user input etc) and write these files before bringing up the services. Alternatively, a directory - `secrets` - could be created and passed into the init container as rw, with it handling the generation if the files don't already exist. Similarly, `./restart -r` can nuke and regenerate these as required.

As the .env file already ships with this repo and is checked into source control, this also prevents users from accidentally committing any secrets as part of their downstream versioning too.

**Comment by KimBurgess** [comment]
@qk4 and @w-le any other approaches that will keep things here close-ish to prod environments?

**Comment by stakach** [comment]
Seems like a good approach. We could create a shard that wraps the functionality up so it's almost as simple as using `ENV` in our code. That lib could also could check an ENV var to see if it should fallback to ENV or the file system mount - which would make testing simpler as we could continue to use ENV vars for specs

**Comment by stakach** [comment]
Also need to consider backups / re-building a cluster
we don't want to loose the secrets if a production cluster needs to be re-built

**Comment by KimBurgess** [comment]
I've put together a simple shard to handle these reads. Should just be required and it'll do the rest. https://github.com/place-labs/secrets-env.

**Comment by stakach** [comment]
Love the implementation
